[package]
name = "nn_entropy"
version = "0.2.0"
edition = "2024"

[lib]
name = "nn_entropy"
crate-type = ["cdylib", "rlib"]

[dependencies]
kiddo = "5.0.3"
rayon = "1.5"
numpy = "0.21"
pyo3 = { version = "0.21", features = ["extension-module"] }

[dev-dependencies]
assert_approx_eq = "1.1.0"

[profile.release]
lto = "fat"     
codegen-units = 1

[features]
fma = []
