//! Shared helpers for the scientific correctness suite.
//!
//! Everything here is deliberately independent of `nn_entropy`'s internals: the
//! random streams are generated by a self-contained algorithm, the
//! nearest-neighbor reference is a brute-force O(N^2) scan, and the entropy
//! constant is rebuilt from its definition. Nothing in this module may call the
//! optimized code paths it is used to check.

#![allow(dead_code)]

use nn_entropy::CoordinateMetric;

/// Euler-Mascheroni constant, to the precision the crate itself uses.
pub const EULER_MASCHERONI: f64 = 0.57721566490153;

// ---------------------------------------------------------------------------
// Deterministic sampling
// ---------------------------------------------------------------------------

/// SplitMix64. Chosen over `rand::StdRng` so the sample streams are fixed by
/// this file alone and cannot drift when a dependency changes its generator.
pub struct Rng(u64);

impl Rng {
    pub fn new(seed: u64) -> Self {
        Rng(seed)
    }

    fn next_u64(&mut self) -> u64 {
        self.0 = self.0.wrapping_add(0x9E37_79B9_7F4A_7C15);
        let mut z = self.0;
        z = (z ^ (z >> 30)).wrapping_mul(0xBF58_476D_1CE4_E5B9);
        z = (z ^ (z >> 27)).wrapping_mul(0x94D0_49BB_1331_11EB);
        z ^ (z >> 31)
    }

    /// Uniform on [0, 1), using 53 bits of mantissa.
    pub fn uniform(&mut self) -> f64 {
        (self.next_u64() >> 11) as f64 / (1u64 << 53) as f64
    }

    /// Uniform on [low, high).
    pub fn uniform_range(&mut self, low: f64, high: f64) -> f64 {
        low + (high - low) * self.uniform()
    }

    /// Standard normal via the Box-Muller transform.
    pub fn normal(&mut self) -> f64 {
        // Guard against log(0); `uniform` can return exactly 0.
        let mut u1 = self.uniform();
        while u1 <= f64::MIN_POSITIVE {
            u1 = self.uniform();
        }
        let u2 = self.uniform();
        (-2.0 * u1.ln()).sqrt() * (std::f64::consts::TAU * u2).cos()
    }

    /// Exponential with rate `lambda`, by inverse CDF.
    pub fn exponential(&mut self, lambda: f64) -> f64 {
        let mut u = self.uniform();
        while u <= f64::MIN_POSITIVE {
            u = self.uniform();
        }
        -u.ln() / lambda
    }

    pub fn uniform_vec(&mut self, n: usize, low: f64, high: f64) -> Vec<f64> {
        (0..n).map(|_| self.uniform_range(low, high)).collect()
    }

    pub fn normal_vec(&mut self, n: usize, mean: f64, std_dev: f64) -> Vec<f64> {
        (0..n).map(|_| mean + std_dev * self.normal()).collect()
    }

    pub fn exponential_vec(&mut self, n: usize, lambda: f64) -> Vec<f64> {
        (0..n).map(|_| self.exponential(lambda)).collect()
    }

    /// A correlated standard bivariate normal pair with correlation `rho`.
    pub fn correlated_normal_pair(&mut self, n: usize, rho: f64) -> (Vec<f64>, Vec<f64>) {
        let mut xs = Vec::with_capacity(n);
        let mut ys = Vec::with_capacity(n);
        for _ in 0..n {
            let z1 = self.normal();
            let z2 = self.normal();
            xs.push(z1);
            ys.push(rho * z1 + (1.0 - rho * rho).sqrt() * z2);
        }
        (xs, ys)
    }
}

// ---------------------------------------------------------------------------
// Closed-form differential entropies (natural log units)
// ---------------------------------------------------------------------------

/// Uniform on an interval of width `width`: H = ln(width).
pub fn uniform_entropy(width: f64) -> f64 {
    width.ln()
}

/// Normal with standard deviation `sigma`: H = 1/2 ln(2 pi e sigma^2).
pub fn normal_entropy(sigma: f64) -> f64 {
    0.5 * (std::f64::consts::TAU * std::f64::consts::E * sigma * sigma).ln()
}

/// Exponential with rate `lambda`: H = 1 - ln(lambda).
pub fn exponential_entropy(lambda: f64) -> f64 {
    1.0 - lambda.ln()
}

/// Bivariate normal with unit marginals and correlation `rho`:
/// H = ln(2 pi e) + 1/2 ln(1 - rho^2).
pub fn bivariate_normal_entropy(rho: f64) -> f64 {
    (std::f64::consts::TAU * std::f64::consts::E).ln() + 0.5 * (1.0 - rho * rho).ln()
}

/// Mutual information of a bivariate normal: I = -1/2 ln(1 - rho^2).
pub fn bivariate_normal_mutual_information(rho: f64) -> f64 {
    -0.5 * (1.0 - rho * rho).ln()
}

// ---------------------------------------------------------------------------
// Kozachenko-Leonenko constant, rebuilt from its definition
// ---------------------------------------------------------------------------

/// Volume of the unit ball in `dimensions` dimensions.
pub fn unit_ball_volume(dimensions: usize) -> f64 {
    match dimensions {
        1 => 2.0,
        2 => std::f64::consts::PI,
        3 => 4.0 * std::f64::consts::PI / 3.0,
        4 => std::f64::consts::PI.powi(2) / 2.0,
        other => panic!("no unit ball volume for dimension {other}"),
    }
}

/// `ln(V_d) + ln(N) + gamma`, the crate's default (Python-compatible) constant.
pub fn kl_constant_asymptotic(n_frames: usize, dimensions: usize) -> f64 {
    unit_ball_volume(dimensions).ln() + (n_frames as f64).ln() + EULER_MASCHERONI
}

/// `ln(V_d) + H_(N-1)`, the exact finite-sample constant.
pub fn kl_constant_exact(n_frames: usize, dimensions: usize) -> f64 {
    let harmonic: f64 = (1..n_frames).map(|i| 1.0 / i as f64).sum();
    unit_ball_volume(dimensions).ln() + harmonic
}

// ---------------------------------------------------------------------------
// Brute-force nearest-neighbor reference
// ---------------------------------------------------------------------------

fn canonicalize(value: f64, metric: CoordinateMetric) -> f64 {
    match metric {
        CoordinateMetric::Linear => value,
        CoordinateMetric::Periodic { period } => value.rem_euclid(period),
    }
}

fn axis_separation(a: f64, b: f64, metric: CoordinateMetric) -> f64 {
    let delta = (a - b).abs();
    match metric {
        CoordinateMetric::Linear => delta,
        CoordinateMetric::Periodic { period } => delta.min(period - delta),
    }
}

/// Brute-force O(N^2) equivalent of `calc_joint_nn_with_metrics`: the sum over
/// samples of `ln` of the distance to the nearest *distinct* point.
///
/// Matching the crate's documented tie handling, a sample that coincides
/// exactly with others measures to the nearest point at a different position
/// rather than to its own duplicates.
pub fn brute_force_log_nn_sum(coordinates: &[&[f64]], metrics: &[CoordinateMetric]) -> f64 {
    assert_eq!(coordinates.len(), metrics.len());
    let n_points = coordinates[0].len();
    assert!(coordinates.iter().all(|c| c.len() == n_points));

    let point = |index: usize| -> Vec<f64> {
        coordinates
            .iter()
            .zip(metrics)
            .map(|(c, &m)| canonicalize(c[index], m))
            .collect()
    };

    let mut total = 0.0;
    for i in 0..n_points {
        let pi = point(i);
        let mut nearest = f64::INFINITY;
        for j in 0..n_points {
            if i == j {
                continue;
            }
            let pj = point(j);
            let squared: f64 = pi
                .iter()
                .zip(&pj)
                .zip(metrics)
                .map(|((&a, &b), &m)| {
                    let d = axis_separation(a, b, m);
                    d * d
                })
                .sum();
            // Skip exact duplicates: the estimator measures to the nearest
            // point at a *different* position.
            if squared > 0.0 {
                nearest = nearest.min(squared.sqrt());
            }
        }
        assert!(
            nearest.is_finite(),
            "sample {i} has no distinct neighbor; the reference needs >= 2 distinct points"
        );
        total += nearest.ln();
    }
    total
}

/// Joint entropy of the given coordinates, estimated directly from the
/// brute-force nearest-neighbor distances.
pub fn brute_force_joint_entropy(coordinates: &[&[f64]], metrics: &[CoordinateMetric]) -> f64 {
    let dimensions = coordinates.len();
    let n_frames = coordinates[0].len();
    let log_sum = brute_force_log_nn_sum(coordinates, metrics);
    dimensions as f64 * log_sum / n_frames as f64 + kl_constant_asymptotic(n_frames, dimensions)
}

// ---------------------------------------------------------------------------
// Combinatorics
// ---------------------------------------------------------------------------

/// All `k`-subsets of `0..n`, in lexicographic order.
pub fn combinations(n: usize, k: usize) -> Vec<Vec<usize>> {
    let mut out = Vec::new();
    let mut current = Vec::new();
    fn walk(start: usize, n: usize, k: usize, current: &mut Vec<usize>, out: &mut Vec<Vec<usize>>) {
        if current.len() == k {
            out.push(current.clone());
            return;
        }
        for candidate in start..n {
            current.push(candidate);
            walk(candidate + 1, n, k, current, out);
            current.pop();
        }
    }
    walk(0, n, k, &mut current, &mut out);
    out
}

/// Binomial coefficient, computed independently of the crate's version.
pub fn choose(n: usize, k: usize) -> f64 {
    if k > n {
        return 0.0;
    }
    let mut result = 1.0;
    for i in 0..k {
        result *= (n - i) as f64 / (i + 1) as f64;
    }
    result
}
